import { useState } from "react";
import ReactDiffViewer from "react-diff-viewer-continued";
import type { MergedNode, NodeStatus } from "../lib/workflowDiff";
import { stableStringify } from "../lib/workflowDiff";

const STATUS_LABELS: Record<NodeStatus, string> = {
  added: "Added",
  removed: "Removed",
  changed: "Changed",
  unchanged: "Unchanged",
};

type DrawerView = "diff" | "before" | "after";

interface TaskDetailsDrawerProps {
  node: MergedNode;
  onClose: () => void;
}

export function TaskDetailsDrawer({ node, onClose }: TaskDetailsDrawerProps) {
  const [view, setView] = useState<DrawerView>("diff");
  const beforeJson = node.before ? stableStringify(node.before) : "";
  const afterJson = node.after ? stableStringify(node.after) : "";
  const isSynthetic = node.before === null && node.after === null;

  return (
    <aside className="drawer">
      <div className="drawer-header">
        <div className="drawer-titles">
          <h2 className="drawer-name">{node.name}</h2>
          <code className="drawer-ref">{node.ref}</code>
        </div>
        <button className="drawer-close" onClick={onClose} aria-label="Close details">
          ×
        </button>
      </div>

      <div className="drawer-meta">
        <span className="wf-type-chip">{node.type}</span>
        <span className={`status-badge badge-${node.status}`}>
          {STATUS_LABELS[node.status]}
        </span>
      </div>

      {node.status === "changed" ? (
        <nav className="tabs drawer-view-toggle">
          {(["diff", "before", "after"] as const).map(v => (
            <button
              key={v}
              className={`tab${view === v ? " tab-active" : ""}`}
              onClick={() => setView(v)}
            >
              {v === "diff" ? "Diff" : v === "before" ? "Before" : "After"}
            </button>
          ))}
        </nav>
      ) : null}

      <div className="drawer-body">
        {isSynthetic ? (
          <p className="drawer-note">
            Synthetic node generated by the graph builder — no task definition.
          </p>
        ) : node.status === "changed" ? (
          view === "diff" ? (
            <div className="drawer-diff">
              <ReactDiffViewer
                oldValue={beforeJson}
                newValue={afterJson}
                splitView={false}
                // Task JSONs are small — show full context so there are no
                // "@@ … @@" fold bars. ponytail: a pathological huge task still
                // folds past 60 lines; raise if that ever bites.
                extraLinesSurroundingDiff={60}
                useDarkTheme={false}
                // Wrap long values (URIs, expressions) instead of forcing a
                // horizontal scrollbar.
                styles={{
                  contentText: { whiteSpace: "pre-wrap", wordBreak: "break-word" },
                }}
              />
            </div>
          ) : (
            <pre className="drawer-json">
              {view === "before" ? beforeJson : afterJson}
            </pre>
          )
        ) : (
          <>
            <div className="drawer-json-title">
              {node.status === "removed" ? "Task JSON (Before)" : "Task JSON (After)"}
            </div>
            <pre className="drawer-json">{node.after ? afterJson : beforeJson}</pre>
          </>
        )}
      </div>
    </aside>
  );
}
