import ReactDiffViewer from "react-diff-viewer-continued";
import type { MergedNode, NodeStatus } from "../lib/workflowDiff";
import { stableStringify } from "../lib/workflowDiff";

const STATUS_LABELS: Record<NodeStatus, string> = {
  added: "Added",
  removed: "Removed",
  changed: "Changed",
  unchanged: "Unchanged",
};

interface TaskDetailsDrawerProps {
  node: MergedNode;
  onClose: () => void;
}

export function TaskDetailsDrawer({ node, onClose }: TaskDetailsDrawerProps) {
  const beforeJson = node.before ? stableStringify(node.before) : "";
  const afterJson = node.after ? stableStringify(node.after) : "";
  const isSynthetic = node.before === null && node.after === null;

  return (
    <aside className="drawer">
      <div className="drawer-header">
        <div className="drawer-titles">
          <h2 className="drawer-name">{node.name}</h2>
          <code className="drawer-ref">{node.ref}</code>
        </div>
        <button className="drawer-close" onClick={onClose} aria-label="Close details">
          ×
        </button>
      </div>

      <div className="drawer-meta">
        <span className="wf-type-chip">{node.type}</span>
        <span className={`status-badge badge-${node.status}`}>
          {STATUS_LABELS[node.status]}
        </span>
      </div>

      <div className="drawer-body">
        {isSynthetic ? (
          <p className="drawer-note">
            Synthetic node generated by the graph builder — no task definition.
          </p>
        ) : node.status === "changed" ? (
          <div className="drawer-diff">
            <ReactDiffViewer
              oldValue={beforeJson}
              newValue={afterJson}
              splitView
              leftTitle="Before"
              rightTitle="After"
              extraLinesSurroundingDiff={2}
              useDarkTheme={false}
            />
          </div>
        ) : (
          <>
            <div className="drawer-json-title">
              {node.status === "removed" ? "Task JSON (Before)" : "Task JSON (After)"}
            </div>
            <pre className="drawer-json">{node.after ? afterJson : beforeJson}</pre>
          </>
        )}
      </div>
    </aside>
  );
}
